language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - docker build -t simple-node --build-arg SAY_HELLO_TO=${SAY_HELLO_TO} .
  - docker tag simple-node ${DOCKER_HUB}/simple-node:latest
  - cd test
  - bash say-hello.sh
  - cd ..

after_success:
  - docker push ${DOCKER_HUB}/simple-node
  - cd test
  - bash say-hello.sh
  - cd ..
